sudo: required
services:
- docker
language: python
python:
- '3.6'
script:
- touch .env
- docker-compose build --build-arg DEVELOPMENT=1 web
- docker-compose up -d
- make test
env:
  global:
  - secure: tGDu9dNoVU4FOG7lzp/HmeHg3Ja1qv85DPBlOXA5XlDw2ti2IoMCqSAqGSMRalGfcMykecdHh0jKWrXk+qBjuuYdsXPNM03+LVBfdhMOzPPT/po5kn0CKA/15I/Vk7RvhYhqYktxn+KM5WhieVXTvJc+mI//Rytn+cyTl8WzKl8VxuNzcwmAO3SK/APvB2RjLMN4riXMce0ZXP9ig0Y8FWUEFFPJ5rXaR36D9Igc/BFyfXHVVHi0HHxmTu3kM6Q+LM94MF8lKNa9pmz4TD90fCM154NSCSNFox7Y3bEqFUR/7GeYYzOK7HpsK2FDoyHq0+aeBfYttVrG4z8O4f+q5DQ2CFj/f1tX3GgYy+8+AjkuKRXT/t187s8Gr3/MNRClyDZBs6ahenSyLkPohB3qO08TD8LQZhDQGOkol342MlQqPpNzLDcPEn8xuQ2W59qkl4LBZ3Q2OQOxqeaAJh+PgWian7l3ohSwt2ki091Eo3kedYZiWvXOueQaqIbcbCbl0ia1REmMw+JnQagpyd4gH9ISiOnnScQjrhpWspEKlNF/3Wz1PuBE+gLp+xP9DRBmcJ1MBd1XWe20QaCUDTf1NhKXDwuw43xPcOWXxfuYk2iJVPmwmy0bhe71fmza5DkhEIBQxO84mKrnZbcifkW/4Lm196OosKlmoPILjYXM4C4=
