version: '3'

services:

  # For running the Flask server
  web:
    build:
      context: .
      args:
        DEVELOPMENT: 1
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=xyz
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - MINIO_HOST=minio:9000
      - MINIO_BUCKET_NAME=kbase-cache
      - PYTHONUNBUFFERED=1
      - KBASE_AUTH_URL=https://ci.kbase.us/services/auth
    env_file: .env
    ports:
      - "5001:5000"
    volumes:
      - .:/app

  # For running the file server
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - data:/data
    command: server /data

  # The minio cli interface
  mc:
    image: minio/mc
    volumes:
      - data:/data

volumes:
  data:
