version: '3'

services:

  # For running the Flask server
  web:
    build:
      context: .
      args:
        DEVELOPMENT: 1
    environment:
      - DEVELOPMENT=1
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  # For running the file server
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - data:/data
    command: server /data

  # The minio cli interface
  mc:
    image: minio/mc
    volumes:
      - data:/data

  # A mock kbase auth server (see src/test/mock_auth/endpoints.json)
  auth:
    image: mockservices/mock_json_service
    volumes:
      - ${PWD}/src/test/mock_auth:/config

volumes:
  data:
